import { ModelOption } from "../agents";

// Model options by output type
const textModelOptions: ModelOption[] = [
    // OpenAI GPT-4o and variants
    { value: 'openai/gpt-4o', label: 'GPT-4o' },
    { value: 'gpt-4o', label: 'GPT-4o' },
    { value: 'gpt-4o-2024-08-06', label: 'GPT-4o 2024-08-06' },
    { value: 'gpt-4o-mini', label: 'GPT-4o Mini' },
    { value: 'chatgpt-4o-latest', label: 'ChatGPT-4o Latest' },
    { value: 'gpt-4-turbo', label: 'GPT-4 Turbo' },
    { value: 'gpt-4', label: 'GPT-4' },
    { value: 'gpt-3.5-turbo', label: 'GPT-3.5 Turbo' },
    { value: 'o1-mini', label: 'O1 Mini' },
    { value: 'o3-mini', label: 'O3 Mini' },
    { value: 'gpt-4o-audio-preview', label: 'GPT-4o Audio Preview' },
    { value: 'gpt-4o-mini-audio-preview', label: 'GPT-4o Mini Audio Preview' },
    { value: 'gpt-4o-search-preview', label: 'GPT-4o Search Preview', supportsWebSearch: true, category: 'Web Search' },
    { value: 'gpt-4o-mini-search-preview', label: 'GPT-4o Mini Search Preview', supportsWebSearch: true, category: 'Web Search' },
    { value: 'openai/gpt-4.1-2025-04-14', label: 'GPT-4.1 2025-04-14' },
    { value: 'gpt-4.1-2025-04-14', label: 'GPT-4.1 2025-04-14' },
    { value: 'openai/gpt-4.1-mini-2025-04-14', label: 'GPT-4.1 Mini 2025-04-14' },
    { value: 'gpt-4.1-mini-2025-04-14', label: 'GPT-4.1 Mini 2025-04-14' },
    { value: 'openai/gpt-4.1-nano-2025-04-14', label: 'GPT-4.1 Nano 2025-04-14' },
    { value: 'gpt-4.1-nano-2025-04-14', label: 'GPT-4.1 Nano 2025-04-14' },
    { value: 'openai/o4-mini-2025-04-16', label: 'O4 Mini 2025-04-16' },
    { value: 'o4-mini-2025-04-16', label: 'O4 Mini 2025-04-16' },
    { value: 'openai/o3-2025-04-16', label: 'O3 2025-04-16' },
    { value: 'o3-2025-04-16', label: 'O3 2025-04-16' },
    { value: 'o1', label: 'O1' },
    { value: 'openai/gpt-5-2025-08-07', label: 'GPT-5 2025-08-07' },
    { value: 'gpt-5-2025-08-07', label: 'GPT-5 2025-08-07' },
    { value: 'openai/gpt-5-mini-2025-08-07', label: 'GPT-5 Mini 2025-08-07' },
    { value: 'gpt-5-mini-2025-08-07', label: 'GPT-5 Mini 2025-08-07' },
    { value: 'openai/gpt-5-nano-2025-08-07', label: 'GPT-5 Nano 2025-08-07' },
    { value: 'gpt-5-nano-2025-08-07', label: 'GPT-5 Nano 2025-08-07' },
    { value: 'openai/gpt-5-chat-latest', label: 'GPT-5 Chat Latest' },
    { value: 'gpt-5-chat-latest', label: 'GPT-5 Chat Latest' },

    // Qwen, Mistral, Llama, etc.
    { value: 'Qwen/Qwen2-72B-Instruct', label: 'Qwen2-72B Instruct' },
    { value: 'mistralai/Mixtral-8x7B-Instruct-v0.1', label: 'Mixtral 8x7B Instruct v0.1' },
    { value: 'meta-llama/Llama-3.3-70B-Instruct-Turbo', label: 'Llama 3.3 70B Instruct Turbo' },
    { value: 'meta-llama/Llama-3.2-3B-Instruct-Turbo', label: 'Llama 3.2 3B Instruct Turbo' },
    { value: 'meta-llama/Llama-Guard-3-11B-Vision-Turbo', label: 'Llama Guard 3 11B Vision Turbo' },
    { value: 'Qwen/Qwen2.5-7B-Instruct-Turbo', label: 'Qwen2.5 7B Instruct Turbo' },
    { value: 'Qwen/Qwen2.5-Coder-32B-Instruct', label: 'Qwen2.5 Coder 32B Instruct' },
    { value: 'meta-llama/Meta-Llama-3-8B-Instruct-Lite', label: 'Meta-Llama 3 8B Instruct Lite' },
    { value: 'meta-llama/Llama-3-70b-chat-hf', label: 'Llama 3 70B Chat HF' },
    { value: 'Qwen/Qwen2.5-72B-Instruct-Turbo', label: 'Qwen2.5 72B Instruct Turbo' },
    { value: 'Qwen/QwQ-32B', label: 'QwQ 32B' },
    { value: 'meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo', label: 'Meta-Llama 3.1 405B Instruct Turbo' },
    { value: 'meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo', label: 'Meta-Llama 3.1 8B Instruct Turbo' },
    { value: 'meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo', label: 'Meta-Llama 3.1 70B Instruct Turbo' },
    { value: 'mistralai/Mistral-7B-Instruct-v0.2', label: 'Mistral 7B Instruct v0.2' },
    { value: 'meta-llama/LlamaGuard-2-8b', label: 'LlamaGuard 2 8B' },
    { value: 'mistralai/Mistral-7B-Instruct-v0.1', label: 'Mistral 7B Instruct v0.1' },
    { value: 'mistralai/Mistral-7B-Instruct-v0.3', label: 'Mistral 7B Instruct v0.3' },
    { value: 'meta-llama/Meta-Llama-Guard-3-8B', label: 'Meta-Llama Guard 3 8B' },
    { value: 'meta-llama/llama-4-scout', label: 'Llama 4 Scout' },
    { value: 'meta-llama/Llama-4-Scout-17B-16E-Instruct', label: 'Llama 4 Scout 17B 16E Instruct' },
    { value: 'meta-llama/llama-4-maverick', label: 'Llama 4 Maverick' },
    { value: 'meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8', label: 'Llama 4 Maverick 17B 128E Instruct FP8' },
    { value: 'Qwen/Qwen3-235B-A22B-fp8-tput', label: 'Qwen3 235B A22B FP8 TPUT' },

    // Anthropic Claude
    { value: 'claude-3-opus-20240229', label: 'Claude 3 Opus 20240229', category: 'Anthropic' },
    { value: 'anthropic/claude-3-opus-20240229', label: 'Claude 3 Opus 20240229', category: 'Anthropic' },
    { value: 'anthropic/claude-3-opus', label: 'Claude 3 Opus', category: 'Anthropic' },
    { value: 'claude-3-opus-latest', label: 'Claude 3 Opus Latest', category: 'Anthropic' },
    { value: 'claude-3-haiku-20240307', label: 'Claude 3 Haiku 20240307', category: 'Anthropic' },
    { value: 'anthropic/claude-3-haiku-20240307', label: 'Claude 3 Haiku 20240307', category: 'Anthropic' },
    { value: 'anthropic/claude-3-haiku', label: 'Claude 3 Haiku', category: 'Anthropic' },
    { value: 'claude-3-haiku-latest', label: 'Claude 3 Haiku Latest', category: 'Anthropic' },
    { value: 'claude-3-5-sonnet-20240620', label: 'Claude 3.5 Sonnet 20240620', category: 'Anthropic' },
    { value: 'anthropic/claude-3.5-sonnet-20240620', label: 'Claude 3.5 Sonnet 20240620', category: 'Anthropic' },
    { value: 'claude-3-5-sonnet-20241022', label: 'Claude 3.5 Sonnet 20241022', category: 'Anthropic' },
    { value: 'anthropic/claude-3.5-sonnet-20241022', label: 'Claude 3.5 Sonnet 20241022', category: 'Anthropic' },
    { value: 'anthropic/claude-3.5-sonnet', label: 'Claude 3.5 Sonnet', category: 'Anthropic' },
    { value: 'claude-3-5-sonnet-latest', label: 'Claude 3.5 Sonnet Latest', category: 'Anthropic' },
    { value: 'claude-3-5-haiku-20241022', label: 'Claude 3.5 Haiku 20241022', category: 'Anthropic' },
    { value: 'anthropic/claude-3-5-haiku-20241022', label: 'Claude 3.5 Haiku 20241022', category: 'Anthropic' },
    { value: 'anthropic/claude-3-5-haiku', label: 'Claude 3.5 Haiku', category: 'Anthropic' },
    { value: 'claude-3-5-haiku-latest', label: 'Claude 3.5 Haiku Latest', category: 'Anthropic' },
    { value: 'claude-3-7-sonnet-20250219', label: 'Claude 3.7 Sonnet 20250219', category: 'Anthropic' },
    { value: 'claude-3-7-sonnet-latest', label: 'Claude 3.7 Sonnet Latest', category: 'Anthropic' },
    { value: 'anthropic/claude-3.7-sonnet', label: 'Claude 3.7 Sonnet', category: 'Anthropic' },
    { value: 'claude-sonnet-4-20250514', label: 'Claude Sonnet 4 20250514', category: 'Anthropic' },
    { value: 'anthropic/claude-sonnet-4', label: 'Claude Sonnet 4', category: 'Anthropic' },
    { value: 'anthropic/claude-sonnet-4-20250514', label: 'Claude Sonnet 4 20250514', category: 'Anthropic' },
    { value: 'claude-sonnet-4-latest', label: 'Claude Sonnet 4 Latest', category: 'Anthropic' },
    { value: 'claude-opus-4-20250514', label: 'Claude Opus 4 20250514', category: 'Anthropic' },
    { value: 'anthropic/claude-opus-4', label: 'Claude Opus 4', category: 'Anthropic' },
    { value: 'anthropic/claude-opus-4-20250514', label: 'Claude Opus 4 20250514', category: 'Anthropic' },
    { value: 'claude-opus-4-latest', label: 'Claude Opus 4 Latest', category: 'Anthropic' },
    { value: 'claude-opus-4-1-20250805', label: 'Claude Opus 4.1 20250805', category: 'Anthropic' },
    { value: 'claude-opus-4-1', label: 'Claude Opus 4.1', category: 'Anthropic' },
    { value: 'anthropic/claude-opus-4.1', label: 'Claude Opus 4.1', category: 'Anthropic' },

    // Gemini
    { value: 'google/gemini-2.0-flash-exp', label: 'Gemini 2.0 Flash Exp' },
    { value: 'gemini-2.0-flash-exp', label: 'Gemini 2.0 Flash Exp' },
    { value: 'google/gemini-2.0-flash', label: 'Gemini 2.0 Flash' },
    { value: 'gemini-2.0-flash', label: 'Gemini 2.0 Flash' },
    { value: 'google/gemini-2.5-pro', label: 'Gemini 2.5 Pro' },
    { value: 'gemini-2.5-pro', label: 'Gemini 2.5 Pro' },
    { value: 'google/gemini-2.5-flash', label: 'Gemini 2.5 Flash' },
    { value: 'gemini-2.5-flash', label: 'Gemini 2.5 Flash' },
    { value: 'google/gemini-2.5-flash-lite-preview', label: 'Gemini 2.5 Flash Lite Preview' },

    // DeepSeek
    { value: 'deepseek-chat', label: 'DeepSeek Chat' },
    { value: 'deepseek/deepseek-chat-v3-0324', label: 'DeepSeek Chat v3 0324' },
    { value: 'deepseek-reasoner', label: 'DeepSeek Reasoner' },
    { value: 'deepseek/deepseek-r1', label: 'DeepSeek R1' },
    { value: 'deepseek/deepseek-chat-v3.1', label: 'DeepSeek Chat v3.1' },
    { value: 'deepseek/deepseek-chat', label: 'DeepSeek Chat' },
    { value: 'deepseek/deepseek-reasoner-v3.1', label: 'DeepSeek Reasoner v3.1' },
    { value: 'deepseek/deepseek-reasoner', label: 'DeepSeek Reasoner' },
    { value: 'deepseek/deepseek-prover-v2', label: 'DeepSeek Prover v2' },

    // Alibaba Qwen
    { value: 'alibaba/qwen-max', label: 'Qwen Max' },
    { value: 'qwen-max', label: 'Qwen Max' },
    { value: 'alibaba/qwen-plus', label: 'Qwen Plus' },
    { value: 'qwen-plus', label: 'Qwen Plus' },
    { value: 'alibaba/qwen-turbo', label: 'Qwen Turbo' },
    { value: 'qwen-turbo', label: 'Qwen Turbo' },
    { value: 'alibaba/qwen-max-2025-01-25', label: 'Qwen Max 2025-01-25' },
    { value: 'qwen-max-2025-01-25', label: 'Qwen Max 2025-01-25' },
    { value: 'alibaba/qwen3-coder-480b-a35b-instruct', label: 'Qwen3 Coder 480B A35B Instruct' },
    { value: 'qwen3-coder-480b-a35b-instruct', label: 'Qwen3 Coder 480B A35B Instruct' },
    { value: 'alibaba/qwen3-32b', label: 'Qwen3 32B' },
    { value: 'qwen3-32b', label: 'Qwen3 32B' },
    { value: 'alibaba/qwen3-max-preview', label: 'Qwen3 Max Preview' },
    { value: 'qwen3-max-preview', label: 'Qwen3 Max Preview' },
    { value: 'alibaba/qwen3-235b-a22b-thinking-2507', label: 'Qwen3 235B A22B Thinking 2507' },
    { value: 'qwen3-235b-a22b-thinking-2507', label: 'Qwen3 235B A22B Thinking 2507' },
    { value: 'alibaba/qwen3-next-80b-a3b-thinking', label: 'Qwen3 Next 80B A3B Thinking' },
    { value: 'qwen3-next-80b-a3b-thinking', label: 'Qwen3 Next 80B A3B Thinking' },
    { value: 'alibaba/qwen3-next-80b-a3b-instruct', label: 'Qwen3 Next 80B A3B Instruct' },
    { value: 'qwen3-next-80b-a3b-instruct', label: 'Qwen3 Next 80B A3B Instruct' },

    // Mistral
    { value: 'mistralai/mistral-tiny', label: 'Mistral Tiny' },
    { value: 'mistralai/mistral-nemo', label: 'Mistral Nemo' },
    { value: 'mistralai/codestral-2501', label: 'Codestral 2501' },

    // Anthracite, Nvidia, MiniMax, Bagoodex, Moonshot, Grok, Perplexity, Zhipu
    { value: 'anthracite-org/magnum-v4-72b', label: 'Magnum v4 72B' },
    { value: 'nvidia/llama-3.1-nemotron-70b-instruct', label: 'Llama 3.1 Nemotron 70B Instruct' },
    { value: 'google/gemma-3-4b-it', label: 'Gemma 3 4B IT' },
    { value: 'google/gemma-3-12b-it', label: 'Gemma 3 12B IT' },
    { value: 'google/gemma-3-27b-it', label: 'Gemma 3 27B IT' },
    { value: 'google/gemma-3n-e4b-it', label: 'Gemma 3N E4B IT' },
    { value: 'cohere/command-a', label: 'Cohere Command A' },
    { value: 'openai/gpt-oss-120b', label: 'GPT OSS 120B' },
    { value: 'openai/gpt-oss-20b', label: 'GPT OSS 20B' },
    { value: 'nousresearch/hermes-4-405b', label: 'Hermes 4 405B' },
    { value: 'MiniMax-Text-01', label: 'MiniMax Text 01' },
    { value: 'minimax/m1', label: 'MiniMax M1' },
    { value: 'MiniMax-M1', label: 'MiniMax M1' },
    { value: 'bagoodex/bagoodex-search-v1', label: 'AI Search Engine', category: 'AI Agent' },
    { value: 'moonshot/kimi-k2-preview', label: 'Moonshot Kimi K2 Preview', supportsWebSearch: true, category: 'Web Search' },
    { value: 'kimi-k2-0711-preview', label: 'Kimi K2 0711 Preview' },
    { value: 'x-ai/grok-4-07-09', label: 'Grok 4 07-09' },
    { value: 'grok-4-0709', label: 'Grok 4 0709' },
    { value: 'x-ai/grok-3-beta', label: 'Grok 3 Beta' },
    { value: 'grok-3', label: 'Grok 3' },
    { value: 'x-ai/grok-3-mini-beta', label: 'Grok 3 Mini Beta' },
    { value: 'grok-3-mini', label: 'Grok 3 Mini' },
    { value: 'x-ai/grok-code-fast-1', label: 'Grok Code Fast 1' },
    { value: 'grok-code-fast-1', label: 'Grok Code Fast 1' },
    { value: 'perplexity/sonar', label: 'Perplexity Sonar', supportsWebSearch: true, category: 'Web Search' },
    { value: 'sonar', label: 'Sonar', supportsWebSearch: true, category: 'Web Search' },
    { value: 'perplexity/sonar-pro', label: 'Perplexity Sonar Pro', supportsWebSearch: true, category: 'Web Search' },
    { value: 'sonar-pro', label: 'Sonar Pro', supportsWebSearch: true, category: 'Web Search' },
    { value: 'zhipu/glm-4.5', label: 'GLM 4.5' },
    { value: 'glm-4.5', label: 'GLM 4.5' },
    { value: 'zhipu/glm-4.5-air', label: 'GLM 4.5 Air' },
    { value: 'glm-4.5-air', label: 'GLM 4.5 Air' },
];

const imageModelOptions: ModelOption[] = [
    { value: 'flux/srpo', label: 'Flux Spro' },
    { value: 'flux/dev', label: 'Flux Dev' },
    { value: 'google/imagen-4.0-generate-001', label: 'Imagegen 4.0 Generate' },
    { value: 'google/imagen-4.0-ultra-generate-001', label: 'Imagegen 4.0 Ultra' },
    { value: 'google/gemini-2.5-flash-image', label: "Gemini 2.5 Flash Image" },
];

const videoModelOptions: ModelOption[] = [
    { value: 'openai/sora', label: 'Sora' },
    { value: 'openai/sora-1.0', label: 'Sora 1.0' },
    { value: 'openai/sora-1.0-turbo', label: 'Sora 1.0 Turbo' },
    { value: 'stability-ai/stable-video-diffusion-img2vid-xt-1-1', label: 'Stable Video Diffusion Img2Vid XT 1.1' },
    { value: 'stability-ai/stable-video-diffusion-img2vid', label: 'Stable Video Diffusion Img2Vid' },
    { value: 'runwayml/gen-3-alpha', label: 'Runway Gen-3 Alpha' },
    { value: 'runwayml/gen-3', label: 'Runway Gen-3' },
    { value: 'runwayml/gen-2', label: 'Runway Gen-2' },
    { value: 'luma-labs/dream-machine', label: 'Luma Dream Machine' },
    { value: 'klingai/kling-v1', label: 'Kling v1' },
    { value: 'google/veo', label: 'Veo' },
    { value: 'google/veo-1.0', label: 'Veo 1.0' },
    { value: 'google/veo-1.0-pro', label: 'Veo 1.0 Pro' },
    { value: 'openai/sora-mini', label: 'Sora Mini' },
    { value: 'openai/sora-mini-1.0', label: 'Sora Mini 1.0' },
    { value: 'stability-ai/stable-video-3d', label: 'Stable Video 3D' },
    { value: 'pika-labs/pika-1.5', label: 'Pika 1.5' },
    { value: 'pika-labs/pika-1.0', label: 'Pika 1.0' },
    { value: 'animatediff/animatediff-xl', label: 'AnimateDiff XL' },
];

const speechModelOptions: ModelOption[] = [
    { value: 'openai/whisper-1', label: 'Whisper v1' },
    { value: 'openai/whisper-large-v3', label: 'Whisper Large v3' },
    { value: 'openai/whisper-large-v3-turbo', label: 'Whisper Large v3 Turbo' },
    { value: 'openai/tts-1', label: 'TTS-1' },
    { value: 'openai/tts-1-hd', label: 'TTS-1 HD' },
    { value: 'openai/tts-1-1106', label: 'TTS-1 1106' },
    { value: 'openai/tts-1-hd-1106', label: 'TTS-1 HD 1106' },
    { value: 'elevenlabs/eleven-multilingual-v2', label: 'Eleven Multilingual v2' },
    { value: 'elevenlabs/eleven-multilingual-v1', label: 'Eleven Multilingual v1' },
    { value: 'elevenlabs/eleven-english-v2', label: 'Eleven English v2' },
    { value: 'elevenlabs/eleven-turbo-v2', label: 'Eleven Turbo v2' },
    { value: 'elevenlabs/eleven-turbo-v2-5', label: 'Eleven Turbo v2.5' },
    { value: 'google/gemini-2.0-flash-thinking-exp-01-21', label: 'Gemini 2.0 Flash Thinking Exp' },
    { value: 'google/text-to-speech', label: 'Google Text-to-Speech' },
    { value: 'google/text-to-speech-premium', label: 'Google Text-to-Speech Premium' },
    { value: 'google/wavenet', label: 'Google WaveNet' },
    { value: 'amazon/polly', label: 'Amazon Polly' },
    { value: 'microsoft/azure-speech', label: 'Azure Speech' },
    { value: 'openai/voice-cloning-v1', label: 'OpenAI Voice Cloning v1' },
    { value: 'elevenlabs/voice-cloning-v1', label: 'ElevenLabs Voice Cloning v1' },
    { value: 'openai/whisper-realtime-v1', label: 'Whisper Realtime v1' },
    { value: 'openai/whisper-realtime-v1-2024-12-17', label: 'Whisper Realtime v1 2024-12-17' },
  ];

export { textModelOptions, imageModelOptions, videoModelOptions, speechModelOptions };